services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    mem_limit: 1g

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    mem_limit: 1g
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 7s
      timeout: 5s
      retries: 3

  stats_service:
    build:
      context: stats_service
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER:-kafka:9092}
      TOPIC_USER_STATS: ${TOPIC_USER_STATS:-user-stats}
      DB_STATS_HOST: pg_stats
    env_file:
      - .env
    command: /bin/sh -c "alembic upgrade head && python3 app/main.py"
    depends_on:
      pg_stats:
        condition: service_healthy
    mem_limit: 1g

  recommendation_service:
    build:
      context: recommendation_service
    environment:
      DB_RECOMMEND_HOST: pg_recommend
    env_file:
      - .env
    command: /bin/sh -c "alembic upgrade head && python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      pg_recommend:
        condition: service_healthy

    ports:
      - 8004:8000
    mem_limit: 1g


  ml_service:
    build:
      context: ml_service
    environment:
      DB_RECOMMEND_HOST: pg_recommend
      DB_STATS_HOST: pg_stats
    env_file:
      - .env
    mem_limit: 8g

    depends_on:
      pg_recommend:
        condition: service_healthy
      pg_stats:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 8g
      

  pg_stats:
    image: postgres:14
    container_name: pg_stats
    volumes:
      - stats_pg:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: db_stats
      POSTGRES_USER: db_stats
      POSTGRES_PASSWORD: db_stats

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db_stats", "-U", "db_stats"] 
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 1g



  pg_recommend:
    image: postgres:14
    container_name: pg_recommend
    volumes:
      - recommend_pg:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: db_recommend
      POSTGRES_USER: db_recommend
      POSTGRES_PASSWORD: db_recommend

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db_recommend", "-U", "db_recommend"] 
      interval: 10s
      timeout: 5s
      retries: 5
    mem_limit: 1g


  producer:
    build:
      context: main
    ports:
      - "8001:8000"
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER:-kafka:9092}
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minio123}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minio123}
      RECOMMENDATION_SERVICE_URL: recommendation_service
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
      minio:
        condition: service_started

  db:
    image: postgres:16-alpine3.21
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mydatabase}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-myuser} -d ${POSTGRES_DB:-mydatabase}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
   image: minio/minio:latest
   command: server --console-address ":9001" /data/
   ports:
     - "9000:9000"
     - "9001:9001"
   environment:
     MINIO_ROOT_USER: minio123
     MINIO_ROOT_PASSWORD: minio123
   volumes:
     - minio-storage:/data
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3

  frontend:
    build:
      context: frontend
    ports:
      - "9010:8504"
    environment:
      MAIN_API_URL: producer
    depends_on:
      producer:
        condition: service_started


volumes:
  stats_pg:
    name: stats_pg
  recommend_pg:
    name: recommend_pg
  postgres_data:
  minio-storage:

