services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 7s
      timeout: 5s
      retries: 3

  stats_service:
    build:
      context: stats_service
    environment:
      KAFKA_BROKER: ${KAFKA_BROKER:-kafka:9092}
      TOPIC_USER_STATS: ${TOPIC_USER_STATS:-user-stats}
      DB_STATS_HOST: pg_stats
    env_file:
      - .env
    command: /bin/sh -c "alembic upgrade head && python3 app/main.py"

  recommendation_service:
    build:
      context: recommendation_service
    environment:
      DB_RECOMMEND_HOST: pg_recommend
    env_file:
      - .env
    command: /bin/sh -c "alembic upgrade head && python -m uvicorn app.main:app --reload --host 0.0.0.0"
    ports:
      - 8000:8000

    depends_on:
      pg_recommend:
        condition: service_healthy

  pg_stats:
    image: postgres:14
    container_name: pg_stats
    volumes:
      - stats_pg:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: db_stats
      POSTGRES_USER: db_stats
      POSTGRES_PASSWORD: db_stats

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db_stats", "-U", "db_stats"] 
      interval: 10s
      timeout: 5s
      retries: 5


  pg_recommend:
    image: postgres:14
    container_name: pg_recommend
    volumes:
      - recommend_pg:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: db_recommend
      POSTGRES_USER: db_recommend
      POSTGRES_PASSWORD: db_recommend

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "db_recommend", "-U", "db_recommend"] 
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  stats_pg:
    name: stats_pg

  recommend_pg:
    name: recommend_pg